### ISSUE TITLE
Parser should be case insensitive

### ISSUE THREAD

**Issue by neverendingqs** [jslicense/spdx-expression-parse.js#23]
According to the [SPDX License List Matching Guidelines](https://spdx.org/spdx-license-list/matching-guidelines), SPDX license identifiers can be case insensitive:

> 4. Capitalization

> 4.1 Purpose:  To avoid the possibility of a non-match due to lower case or upper case letters in otherwise the same words.

> 4.1.1 Guideline:  All **upper case and lower case letters should be treated as lower case letters**. Templates do not include markup for this guideline.

However, the following shows casing matters when it shouldn't:

```js
'use strict';

// spdx-expression-parse@3.0.0
const parse = require('spdx-expression-parse');

// This works
console.log(parse('Apache-2.0'));

// This throws an error, but it shouldn't
console.log(parse('APACHE-2.0'));
```
(You can run it at https://repl.it/@neverendingqs/spdx-expression-parse-case-sensitivity).

**Comment by kemitchell** [comment]
@neverendingqs, I believe the Matching Guidelines you refer to cover matching of _license texts_ to the standardized text of the various licenses SPDX has standardized, rather than matching identifiers for those licenses. Thus a `LICENSE` file may still be coded `MIT` if it says `MIT LICENSE` at the top instead of `MIT License`, as in the standard form. But the correct SPDX identifier for that license is `MIT` and only `MIT`. Not `mit`, `MiT`, &c.
